In [8]:
import numpy as np
# Nutrient requirement for 3 crops(n,p,k in kg/ha)
#Rows:crops(wheat,corn,rice)
#columns:Nutrients(Nitrogen ,phosphorous,potassium)
nutrient_needs=np.array([
    [120,60,80],
    [150,75,100],
    [100,50,70]
])

# Available fertilizer composition(percentage of n,p,k)
# Rows: fertilizer types
# columns : nutrient content

fertilizer_composition=np.array([
    [0.20, 0.10, 0.15],
    [0.15, 0.20, 0.10],
    [0.10, 0.15, 0.25]
])
print('Nutrient requirement(kg/ha):')
print(nutrient_needs)
print('\n Fertilizer composition(%):')
print(fertilizer_composition)

# Matrix Transpose example
print('\n Transposed nutrient needs(nutrients x crops):')
print(nutrient_needs.T)

# Calculate fertilizer amounts(Solving system of equations)
# This would normally require optimization but for demonstrtion:
total_nutrients_per_crop=np.sum(nutrient_needs,axis=1)
print(f'\n total nutrients needed per crop:{total_nutrients_per_crop}kg/ha')

# Matrix multiplication: Calculate total nutrient delivery
# if we apply 100kg of each fertilizer type

fertilizer_application=np.array([100,100,100])
nutrients_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f'\n nutrients from 100kg each fertilizer:{nutrients_delivered}')

# calculate determinant(for checking if matrix is invertible)
det=np.linalg.det(fertilizer_composition)
print(f'\n determinant of fertilizer matrix:{det:.6f}')

# identity matrix example (Scaling factor)
Scaling=np.eye(3)*1.1
Enhanced_needs= np.dot(nutrient_needs,Scaling)
print('\n Enhanced nutrient needs(10% increase):')
print(Enhanced_needs)

Nutrient requirement(kg/ha):
[[120  60  80]
 [150  75 100]
 [100  50  70]]

 Fertilizer composition(%):
[[0.2  0.1  0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.25]]

 Transposed nutrient needs(nutrients x crops):
[[120 150 100]
 [ 60  75  50]
 [ 80 100  70]]

 total nutrients needed per crop:[260 325 220]kg/ha

 nutrients from 100kg each fertilizer:[45. 45. 50.]

 determinant of fertilizer matrix:0.004625

 Enhanced nutrient needs(10% increase):
[[132.   66.   88. ]
 [165.   82.5 110. ]
 [110.   55.   77. ]]
