In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A @ B


array([[19, 22],
       [43, 50]])

In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A*B

array([[ 5, 12],
       [21, 32]])

In [2]:
import numpy as np
matrix=np.array([[1,2],[3,4]])
transposed=matrix.T

In [ ]:
matrix=[
    [1,2,3],
    [4,5,6]
]
transpose=list(zip(*matrix))
print("transpose matrix")
for row in transpose:
  print(list(row))

transpose matrix
[1, 4]
[2, 5]
[3, 6]


In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A+B

array([[ 6,  8],
       [10, 12]])

In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A-B

array([[-4, -4],
       [-4, -4]])