In [ ]:
import numpy as np
# From python list
arr=np.array([1,2,3,4,5])
#2D array(matrix)
arr_2d=np.array([[1,2,3],[4,5,6]])
# Using built in functions
zeros=np.zeros((3,4))
ones=np.ones((2,3))
range_arr=np.arange(0,10,2)
linspace=np.linspace(0,1,5)
identity=np.eye(3)
random_arr=np.random.rand(3,4)

print(zeros)
print("===")
print(ones)
print("===")
print(range_arr)
print("===")
print(linspace)
print("===")
print(identity)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
===
[[1. 1. 1.]
 [1. 1. 1.]]
===
[0 2 4 6 8]
===
[0.   0.25 0.5  0.75 1.  ]
===
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)
np.sum(a)


[[1 2 3]
 [4 5 6]]
(2, 3)
int64
6
2


np.int64(21)

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
np.mean(a,axis=0) # column wise mean

array([2.5, 3.5, 4.5])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
np.mean(a,axis=1) # row wise mean

array([2., 5.])

In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[3,4,5]]])
np.mean(a,axis=2)

array([[2., 5.],
       [2., 4.]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
np.max(a)
np.min (a)

np.int64(1)

In [ ]:
b=np.array([10,40,30])
np.argmax(b)

np.int64(1)

In [ ]:
import numpy as np
# Crop yields for 4 farms over 5 seasons(in tons)
crop_yields=np.array([
    [12.5, 13.2, 14.1, 13.8, 15.2],
    [10.3, 11.5, 10.8, 12.1, 11.9],
    [15.1, 14.8, 16.2, 15.5, 16.8],
    [11.2, 10.9, 12.3, 11.7, 12.8]
    ])
print('crop yields array(tons):')
print(crop_yields)
print(f'\n shape: {crop_yields.shape}')
print(f'Data type:{crop_yields.dtype}')
print(f'Total elements:{crop_yields.size}')
print(f'Number of dimensions:{crop_yields.ndim}')

# Agriculture analysis operations

total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f'\n Total production:{total_yield}tons')
print(f'Average per farm:{avg_yield_per_farm}tons')
print(f'Average per season:{avg_yield_per_season}tons')
print(f'Maximum yield:{max_yield}tons')
print(f'Minimum yield:{min_yield}tons')

# Find best performing farm

best_farm=np.argmax(avg_yield_per_farm)
print(f'\n BEST PERFORMING FARM: farm{best_farm+1}')
print(f' Their average yield:{avg_yield_per_farm[best_farm]:.2f}tons')

crop yields array(tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

 shape: (4, 5)
Data type:float64
Total elements:20
Number of dimensions:2

 Total production:262.7tons
Average per farm:[13.76 11.32 15.68 11.78]tons
Average per season:[12.275 12.6   13.35  13.275 14.175]tons
Maximum yield:16.8tons
Minimum yield:10.3tons

 BEST PERFORMING FARM: farm3
 Their average yield:15.68tons


In [6]:
import numpy as np
# Crop yields for 4 farms over 5 seasons(in tons)
crop_yields=np.array([
    [12, 13, 14, 13, 15],
    [10, 11, 10, 12, 11],
    [15, 14, 16, 15, 16],
    [11, 10, 12, 11, 12]
    ])
print('crop yields array(tons):')
print(crop_yields)
print(f'\n shape: {crop_yields.shape}')
print(f'Data type:{crop_yields.dtype}')
print(f'Total elements:{crop_yields.size}')
print(f'Number of dimensions:{crop_yields.ndim}')

# Agriculture analysis operations

total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)
linspace=np.linspace(10,20,5)


print(f'\n Total production:{total_yield}tons')
print(f'Average per farm:{avg_yield_per_farm}tons')
print(f'Average per season:{avg_yield_per_season}tons')
print(f'Maximum yield:{max_yield}tons')
print(f'Minimum yield:{min_yield}tons')
print(linspace)

# Find best performing farm

best_farm=np.argmax(avg_yield_per_farm)
print(f'\n BEST PERFORMING FARM: farm{best_farm+1}')
print(f' Their average yield:{avg_yield_per_farm[best_farm]:.2f}tons')

crop yields array(tons):
[[12 13 14 13 15]
 [10 11 10 12 11]
 [15 14 16 15 16]
 [11 10 12 11 12]]

 shape: (4, 5)
Data type:int64
Total elements:20
Number of dimensions:2

 Total production:253tons
Average per farm:[13.4 10.8 15.2 11.2]tons
Average per season:[12.   12.   13.   12.75 13.5 ]tons
Maximum yield:16tons
Minimum yield:10tons
[10.  12.5 15.  17.5 20. ]

 BEST PERFORMING FARM: farm3
 Their average yield:15.20tons
