In [ ]:
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
import numpy as np
x = np.array([2,1,3])
np.argsort(x)

array([1, 0, 2])

In [ ]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[7,8]])
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
a = np.arange(36)
print(a)
b = a.reshape(6,6)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
data = np.array([3,2,1])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[3 2]
[2 1]
[2 1]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])
print("\n")
five_up = (a >= 5)
print(a[five_up])
print("\n")
divisible_by_2 = a[a%2==0]
print(divisible_by_2)
print("\n")
c = a[(a > 2) & (a < 11)]
print(c)
print("\n")
five_up = (a > 5) | (a == 5)
print(five_up)

[1 2 3 4]


[ 5  6  7  8  9 10 11 12]


[ 2  4  6  8 10 12]


[ 3  4  5  6  7  8  9 10]


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])