In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
sum = 0
array = list(range(100))

for i in range(100):
    sum += array[i]

In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array({1,2,3,4,5})
print(arr)

{1, 2, 3, 4, 5}


In [ ]:
import numpy as np
arr=np.array(50)
print(arr)

50


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array(([1,2,3],[4,5,6]))
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np
arr=np.array(([[1,2,3],[4,5,6]]))
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)


[[[[[1 2 3 4 5]]]]]
number of dimensions: 5


In [ ]:
import numpy as np
arr= np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr= np.array([1,2,3,4])
print(arr[0]+arr[3])

5


In [ ]:
# From python list
arr=np.array([1,2,3,4,5])
#2D array(matrix)
arr_2d=np.array([[1,2,3],[4,5,6]])
# Using built in functions
zeros=np.zeros((3,4))
ones=np.ones((2,3))
range_arr=np.arange(0,10,2)
linspace=np.linspace(0,1,5)
identity=np.eye(3)
random_arr=np.random.rand(3,4)

print(zeros)
print("===")
print(ones)
print("===")
print(range_arr)
print("===")
print(linspace)
print("===")
print(identity)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
===
[[1. 1. 1.]
 [1. 1. 1.]]
===
[0 2 4 6 8]
===
[0.   0.25 0.5  0.75 1.  ]
===
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]
