In [ ]:
import numpy as np
a=np.array([1,2,3])
print(2*a)

[2 4 6]


In [ ]:
import numpy as np
a=np.array([1,2,3])
print(2*a)

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
mask=np.array([True,False,True,False,True,False])
b=a[mask]*10
print(b)

[10 30 50]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,0,1],[0,1,0]],dtype=bool)
print(a[b])

[1 3 5]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[a[:,1]%2==0])

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[a%2==0])

[2 4 6]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[a[:,0]%2==0,1])

[]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[:,a[1,:]%2==0])

[[2]
 [4]
 [6]]


In [ ]:
import numpy as np
arr=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

mask=np.array([True,False,True])
print(arr[mask])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[:,[False,True]])

[[2]
 [4]
 [6]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[[False,True,False]])

[[3 4]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[a[:,1]>2])

[[3 4]
 [5 6]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[:,1])

[2 4 6]


In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
idx=np.array([4,0,4,1])
print(a[idx])

[50 10 50 20]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
print(a+b)

[[11 22 33]
 [14 25 36]]


In [ ]:
import numpy as np
a=np.arange(50).reshape(10,5)
selected_rows=a[a[:,0]>20]
print(a[:,0]>20)

[False False False False False  True  True  True  True  True]


In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
mask=(x%2==0)
print(mask)

[False  True False  True False]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[3>a])

[1 2]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[2:])

[3 4 5]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[a>2])

[3 4 5]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[a>=2])

[2 3 4 5]


In [ ]:
import numpy as np
a=np.array([1,2,3])
print(2+a)

[3 4 5]


In [ ]:
import numpy as np
a=np.array([1,2,3])
print(2-a)

[ 1  0 -1]


In [ ]:
import numpy as np
a=np.array([1,2,3])
print(2/a)

[2.         1.         0.66666667]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
print(a-b)

[[ -9 -18 -27]
 [ -6 -15 -24]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[3,4,5]])
print(a+b)

[[11 22 33]
 [ 7  9 11]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[3,4,5]])
print(a*b)

[[10 40 90]
 [12 20 30]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[3,4,5]])
print(a-b)

[[ -9 -18 -27]
 [  1   1   1]]
